version: '3.1'
services:

  server:
    build: ../
    container_name: server
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE: appdb
      - MYSQL_USER: siva
      - MYSQL_PASSWORD: secret
      - MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

